Kp 7226 fetch ms info via oai pmh
CSCfi/Kielipankki-Metax-bridge pull request #1
Opened 2023-06-02 14:24 UTC by kaisakui

This PR contains functionality to fetch all data from Metashare using OAI-PMH protocol.

2023-06-06 13:58 UTC, helhotti requested changes
One python-related comment, otherwise this seems to do what is asked!

2023-06-06 13:58 UTC, helhotti commented on harvester/pmh_interface.py
> +        return metadata_records_list
Is it necessary/a good idea to convert the generator that sickle returns to a list? You probably know best what kind of purposes this function will be used for.

If a list is what you want to return, you can convert the result of `ListRecords` to a list like this:

```
records = list(self.sickle.ListRecords(metadataPrefix="info"))
```
or alternatively only wrap into a list when returning:
```
return list(records)
```

So there's no need for a loop.

2023-06-07 06:03 UTC, helhotti commented on harvester/pmh_interface.py
> +        return metadata_records_list
I just realized that the data type that sickle returns is not a normal generator after all, so my previous comment is pretty much useless :D unless you want to actually return a generator, in which case you could use `yield` in the loop. But if list is what is wanted, this is fine.

2023-06-07 07:35 UTC, kaisakui commented on harvester/pmh_interface.py
> +        return metadata_records_list
Good point! Thanks

2023-06-07 07:38 UTC, helhotti approved these changes
Looks good :+1: I think the generator route may be more future-proof, you can always turn that into a list if needed.

2023-06-08 15:32 UTC, mmatthiesencsc commented
I hoped this to be simple, thanks!

2023-06-08 15:32 UTC, merged